### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by kohtaasa** [kohtaasa/codedoc-assistant#1]
- [x] Visualize a selected library
- [x] Make UI better
- [x] Stream the output
- [ ] Enable users to add new libraries
- [ ] Chat history
